remote_theme: "pages-themes/slate@v0.2.0"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Sujay Talanki's Data Science Portfolio"
description: "Data Scientist | Interested in Predictive Modeling, Deep Learning, and Cloud Computing"
